// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SportShopDbContext))]
    [Migration("20231023144935_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PercentSale")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "adsa@gmail.com",
                            Fullname = "Petruk Stepan Romanovych",
                            Gender = "M",
                            PercentSale = 10,
                            Phone = "0979372948"
                        },
                        new
                        {
                            Id = 2,
                            Email = "fsud@gmail.com",
                            Fullname = "Lyudmila Stepanivna Romanchuk",
                            Gender = "F",
                            PercentSale = 15,
                            Phone = "0959375027"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fullname = "Yaroschuk Ivan Petrovych",
                            Gender = "M",
                            HireDate = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 8500.0
                        },
                        new
                        {
                            Id = 2,
                            Fullname = "Mykhalchuk Ruslana Romanivna",
                            Gender = "F",
                            HireDate = new DateTime(2020, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 8500.0
                        },
                        new
                        {
                            Id = 3,
                            Fullname = "Tetyana Stepanivna Levchuk",
                            Gender = "F",
                            HireDate = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 8500.0
                        },
                        new
                        {
                            Id = 4,
                            Fullname = "Ihor Ivanovich Volos",
                            Gender = "M",
                            HireDate = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Salary = 8500.0
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostPrice")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPrice = 85,
                            Name = "Gloves",
                            Price = 150,
                            Producer = "Turkey",
                            Quantity = 5,
                            Type = "Accessories"
                        },
                        new
                        {
                            Id = 2,
                            CostPrice = 85,
                            Name = "Glasses",
                            Price = 150,
                            Producer = "China",
                            Quantity = 5,
                            Type = "Accessories"
                        },
                        new
                        {
                            Id = 3,
                            CostPrice = 120,
                            Name = "Belt",
                            Price = 250,
                            Producer = "Turkey",
                            Quantity = 15,
                            Type = "Clothes"
                        },
                        new
                        {
                            Id = 4,
                            CostPrice = 400,
                            Name = "Backpack",
                            Price = 700,
                            Producer = "Poland",
                            Quantity = 10,
                            Type = "Accessories"
                        },
                        new
                        {
                            Id = 5,
                            CostPrice = 800,
                            Name = "Adidas sneakers",
                            Price = 1500,
                            Producer = "Poland",
                            Quantity = 20,
                            Type = "Shoes"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            EmployeeId = 1,
                            Price = 10000m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            EmployeeId = 1,
                            Price = 100m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 2,
                            EmployeeId = 2,
                            Price = 1800m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 2,
                            EmployeeId = 4,
                            Price = 10000m,
                            ProductId = 2,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Entities.Sale", b =>
                {
                    b.HasOne("DataAccess.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
